Support multiple remotes
davidraviv/gh-clean-branches pull request #17
Opened 2022-01-03 21:46 UTC by chrisgoffinet

## Related issue:

[Issue ###](https://github.com/davidraviv/gh-clean-branches/issues/###)

## Why did you make this change

## What have you done in this PR

## What was left to do

## Dependencies

## Checklist:

-   [ ] My code follows the style of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have have tested my code locally to prove my fix is effective or that my feature works
-   [ ] I have made corresponding changes to the README.md

2022-01-24 18:37 UTC, davidraviv commented on gh-clean-branches
> +  missing_upstream_branches=(${local_branches:|remote_branches}) # local_branches minus remote_branches
`missing_upstream_branches` will find and delete a local branch that has an upstream in another remote.

Example: 
```bash
⇒  git remote show             
origin-1
origin-2
```

```bash
⇒  git branch -a | cat
* main
  test-branch
  remotes/origin-2/main
  remotes/origin-2/test-branch
  remotes/origin-1/HEAD -> origin/master
  remotes/origin-1/add-module
  remotes/origin-1/main
  remotes/origin-1/master
```
I have two origins, `origin-1` and `origin-2`. 
The local branch `test-branch` has upstream on `origin-2` but doesn't exist on `origin-1`.

When iterating over the upstreams having `upstream_name` as `origin-1`, the branch `test-branch` will be added to `missing_upstream_branches` as it is not included in `remote_branches`. The branch `test-branch` will be deleted in line 79, although it has an upstream in `origin-2`.

2022-01-24 18:40 UTC, davidraviv requested changes
Thanks for the contribution!
Please see my comment.

2022-01-24 21:42 UTC, chrisgoffinet commented
@davidraviv thanks for the review. I'll work on a fix to handle this case.

2022-01-27 19:57 UTC, davidraviv commented
@chrisgoffinet Thanks for the effort in trying to improve the extension.
A [new version](https://github.com/davidraviv/gh-clean-branches/releases/tag/v0.8) is now available that supports multiple upstream.
I hope you can try it out and find it helpful!

2022-01-28 16:17 UTC, closed without merging